FROM node:latest

WORKDIR /app/data/

# RUN npm install -g npm@9.8.0
# RUN npm install
# RUN npm link @angular/cli
# RUN export PATH="$HOME/.npm-packages/bin:$PATH"
# RUN npm uninstall -g @angular/cli
# RUN npm install -g @angular/cli -y

# Start the Angular development server
# CMD ["ng serve --open"]