@endpoint = http://localhost:3000


GET {{endpoint}}/tasks
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuZXN0MyIsImlhdCI6MTY4OTUxOTAxMiwiZXhwIjoxNjg5NTIyNjEyfQ.wSS8s4CtYhDK0CuCwBqafyJ0dJ5cZTrUBWzHHvX1mOU

### Get task by id

GET {{endpoint}}/tasks/487d49b1-1853-4950-bd95-6bc59bd9e5f9


### create a task

POST {{endpoint}}/tasks
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RuZXN0MyIsImlhdCI6MTY4OTUxODM2NiwiZXhwIjoxNjg5NTIxOTY2fQ.oURjTjsdUIL6wu19nNsPU162dw8kNMR4owkNOLKa8NI

{
    "title": "one",
    "description": "two"
}


### delete a task
DELETE {{endpoint}}/tasks/c4978d86-ffff-4f4e-add8-29deb8bf723d


### update task status
PATCH {{endpoint}}/tasks/487d49b1-1853-4950-bd95-6bc59bd9e5f9/status
Content-Type: application/json

{
    "status": "Done"
}

### Get task by id
GET {{endpoint}}/tasks?search=One


### signup User
POST {{endpoint}}/auth/signup
Content-Type: application/json

{
    "username": "testnest",
    "password": "Smkatash987*)"
}

### signin User
POST {{endpoint}}/auth/signin
Content-Type: application/json

{
    "username": "testnest3",
    "password": "Smkatash987*)"
}