export const ROUTE_CHANGE = "router"
export const USER = "user"
export const USER_STATUS = "user-status"
export const ERROR = "error"
export const INGAME = "game"
export const USER_PROFILE = "profile"